FROM golang:1.19 as builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-server

# final stage
FROM scratch

WORKDIR /

COPY --from=builder /app/go-server /
EXPOSE 4040
ENTRYPOINT ["/go-server"]
