FROM golang:1.22

ENV GO111MODULE=on

ENV GOFLAGS=-buildvcs=false

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@v1.50

EXPOSE 4040
ENTRYPOINT ["air"]
